baseurl = "http://csaybar.github.io/"
title = "csaybar"
theme = "hugo-universal-theme"
languageCode = "en-us"
# Site language. Available translations in the theme's `/i18n` directory.
defaultContentLanguage = "en"
# Enable comments by entering your Disqus shortname
disqusShortname = "cesaraybar"
# Enable Google Analytics by entering your tracking code
googleAnalytics = "UA-130564182-1"

# Define the number of posts per page
paginate = 10

[menu]

# Main menu
[[menu.main]]
    identifier="home"
    name = "Home"
    url  = "/"
    weight = 1

[[menu.main]]
    identifier = "research"
    name = "research"
    url  = "/research/"
    weight = 2

[[menu.main]]
    identifier="software"
    name = "software"
    url  = "/software/"
    weight = 3

[[menu.main]]
    identifier="publications"
    name = "publications"
    url  = "/publications/"
    weight = 4

[[menu.main]]
    identifier= "teaching"
    name = "teaching"
    url  = "/teaching/"
    weight = 5

[[menu.main]]
    identifier="blog"
    name = "Blog"
    url  = "/blog/"
    weight = 6

[[menu.main]]
    identifier = "contact"
    name = "Contact"
    url  = "/contact/"
    weight = 7

# Top bar social links menu

[[menu.topbar]]
    weight = 1
    name = "Email"
    url = "mailto:csaybar@gmail.com"
    pre = "<i class='fas fa-2x fa-envelope'></i>"

[[menu.topbar]]
    weight = 2
    name = "Twitter"
    url = "http://twitter.com/csaybar"
    pre = "<i class='fab fa-2x fa-twitter'></i>"


[[menu.topbar]]
    weight = 3
    name = "GitHub"
    url = "https://github.com/csaybar"
    pre = "<i class='fab fa-2x fa-github'></i>"

[[menu.topbar]]
    weight = 4
    name = "ai-google-scholar-square"
    url = "https://scholar.google.com/citations?user=rfF51ocAAAAJ&hl=en"
    pre = "<i class='ai ai-2x ai-google-scholar-square'></i>"
  
[[menu.topbar]]
    weight = 5
    name = "sourcerer"
    url = "https://sourcerer.io/csaybar"
    pre = "<i class='fab fa-stripe-s fa-2x'></i>"

[params]
    viewMorePostLink = "/blog/"
    author = "DevCows"
    defaultKeywords = ["devows", "hugo", "go"]
    mainSections = ["blog"]
    defaultDescription = "Site template made by devcows using hugo"

    # Social media
    facebook_site = "" # the Facebook handle of your site ('https://www.facebook.com/HANDLE')
    twitter_site = "csaybar" # the Twitter handle of your site (without the '@')
    default_sharing_image = "img/sharing-default.png"

    # Google Maps API key (if not set will default to not passing a key.)
    googleMapsApiKey = "AIzaSyBWzxbqlK1u8n0bWqTgnYN7_M9u4LCgiYg"

    # Style options: default (light-blue), blue, green, marsala, pink, red, turquoise, violet
    style = "blue"

    # Since this template is static, the contact form uses www.formspree.io as a
    # proxy. The form makes a POST request to their servers to send the actual
    # email. Visitors can send up to a 1000 emails each month for free.
    #
    # What you need to do for the setup?
    #
    # - set your email address under 'email' below
    # - upload the generated site to your server
    # - send a dummy email yourself to confirm your account
    # - click the confirm link in the email from www.formspree.io
    # - you're done. Happy mailing!
    #
    #Enable the contact form by entering your Formspree.io email
    email = "csaybar@gmail.com"
    contact_form_ajax = false

    about_us = "<p><ul><li>- I have been using Debian OS for 7 years.</li><li>- Brave is my default web browser.</li><li>- I like to watch 90's animes.</li><li>- I like go to camp.</li><li> - I like to cook typical Peruvian food :3.</li><li>- My preferred book is 'deep learning' written by Ian Goodfellow.</ul>"
    copyright = "Copyright (c) 2019, Cesar Aybar Camacho; all rights reserved."

    # Format dates with Go's time formatting
    date_format = "2006-01-02"
    logo = "img/logo.svg"
    logo_small = "img/logo-small.svg"
    address = """<p><strong>Lima</strong>
        <br>Ciudad Universitaria
        <br>Cercado de Lima 
        <br>15081
        <br>
        <strong>Peru</strong>
        <br>
        <br>
      </p>
      """
    latitude = "-12.0560257"
    longitude = "-77.0844226"

[Permalinks]
    blog = "/blog/:year/:month/:day/:filename/"

# Enable or disable top bar with social icons
[params.topbar]
    enable = true
    text = """<p class="hidden-sm hidden-xs"></p>
      <p class="hidden-md hidden-lg"><a href="#" data-animate-hover="pulse"><i class="fas fa-phone"></i></a>
      <a href="#" data-animate-hover="pulse"><i class="fas fa-envelope"></i></a>
      </p>
      """

# Enable and disable widgets for the right sidebar
[params.widgets]
    categories = true
    tags = true
    search = true

[params.carousel]
    enable = true
    # All carousel items are defined in their own files. You can find example items
    # at 'exampleSite/data/carousel'.
    # For more informtion take a look at the README.

[params.features]
    enable = false
    # All features are defined in their own files. You can find example items
    # at 'exampleSite/data/features'.
    # For more informtion take a look at the README.

[params.testimonials]
    enable = false
    # All testimonials are defined in their own files. You can find example items
    # at 'exampleSite/data/testimonials'.
    # For more informtion take a look at the README.
    title = "Testimonials"
    subtitle = "We have worked with many clients and we always like to hear they come out from the cooperation happy and satisfied. Have a look what our clients said about us."

[params.see_more]
    enable = false
    icon = "far fa-file-alt"
    title = "Do you want to see more?"
    subtitle = "We have prepared for you more than 40 different HTML pages, including 5 variations of homepage."
    link_url = "#"
    link_text = "Check other homepages"

[params.clients]
    enable = false
    # All clients are defined in their own files. You can find example items
    # at 'exampleSite/data/clients'.
    # For more informtion take a look at the README.
    title = "Our Clients"
    subtitle = ""

[params.basic]
    enable = true
    title = "From our blog2"
    subtitle = "d"

[params.recent_posts]
enable = true
title = "Algorithms & Maps"
subtitle = "<p><font size='3'>Make a GeoViz or learn how Geospatial algorithms really work, it probably gives you tonnes of fun, isn't that right?. If this isn't your case yet, remember that <b>Geospatial thinking</b> has positioned itself as an essential skill for solving problems in industry and academia, so, learn some geo-stuff will boost definitely your CV. There is a lot to talk about it, but, in this blog, we want to target to:<br><br>- Reproducible examples of Deep Learning and Computer Vision.<br>- State-of-the-art algorithms clearly explained.<br>- Tips about good practices in coding (most of the time Python and R).</br>- And much more!</br><br>I promise to post a new entrance every first week of each month (with probability 0.4)."
